# Generated by Django 4.0.2 on 2022-06-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
