# Generated by Django 4.0.2 on 2022-06-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_System', '0002_customers_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('resiver_name', models.CharField(max_length=100)),
                ('transfer_balance', models.IntegerField()),
            ],
        ),
    ]
